### PR TITLE
Fix/debug data filtering and display

### LINKED ISSUE #6: REACT COMPONENT ARCHITECTURE
PARENT COMPONENT
- [x] App

PAGE COMPONENTS
- [x] EntryPage
- [x] NavPage
- [x] ResultsPage

### LINKED ISSUE #7: CSS BUILD-OUT
PARENT COMPONENT
- [x] App

PAGE COMPONENTS
- [x] EntryPage
- [x] NavPage
- [x] ResultsPage

### LINKED ISSUE #9: ACCESSIBILITY REFACTOR
- Pass WAVE audit
- Pass Lighthouse audit

### LINKED ISSUE #11: TYPECHECKING
- [x] Research PropTypes
- [x] Implement PropTypes

### LINKED ISSUE #18: ROUTER
- [x] Refactored to use Router without leaving artifacts of the prior code
- [x] Shows developer empathy (readability, maintainability)
-  [x] Uses Router components and doesn't manipulate history object
- [ ] A 404 page handles undefined routes
- [ ] UX is excellent; routes are consistent and navigation is clear

### PR DESCRIPTION
**Pull request by pcmueller**
## Is this a fix or a feature?
Both.

## What is the change or fix?
- Debugged "item card" population and display issues by refactoring data filtering and rendering functionality in 'App', 'Results', and 'Card' components.  
- Built and refactored numerous conditional rendering functions to resolve async data-passing/callstack issues, including `componentDidUpdate()`, `buildItemCards()`, and pieces of several others.
- Added multiple data filtering functions to apply different data processing features to different "category" types, via `determineFilter()` and then `filterCreatures()` or `filterItems()`, as well as `buildItemCards()` followed by `useLocalItems()` or `useBackupItems()`.
- Added `screenDuplicates()` function to further assist data filtering by preventing repeat items from being added to `this.state.itemCards`.
- Added numerous Boolean properties to state to be used both in parent state and as props in child components in order to synchronize functionality and data flow: _dataLoaded_, _itemsFiltered_, _usingBackup_, _cardsBuilt_, _isLoading_, _isRandom_, and _hasErrored_.
- Refactored Card.js conditionals to create different "item cards" for elements of different category types, including all data available from each.
- Refactored Main.js "button building" functionality (`buildButtons()` and `handleGoalBtnClick()`) to reduce code and add more fun, custom "button titles" instead of plain category names (e.g. "GIMME THE LOOT" instead of "Treasure").  Also had to refactor "categories" dataset to do this, which has been converted into a proper JS util function file (relocated to `utilities` directory).
- Added `useEffect()` hook to 'Results' component with conditional to render a different "balloon message" for different data results, including that of default state in which "non-local" data is displayed.
- Created 'Loading' and 'Error' components to be used in future error handling and loading state conditional rendering.
- Moved "header" HTML block to new 'Header' component, with conditional functionality to determine appropriate header display for each page.  Refactored 'Entry', 'Main', and 'Results' page components to import and render 'Header'.
- Added PropTypes to all child components.
- Continued styling and formatting item cards in '_results.scss' and '_card.scss', and refactored all Sass partial files to pass Lighthouse accessibility test w/ score of 100.

## Where should the reviewer start?
- Most essential functionality is in App, with data rendering primarily in Results and Card components.  Entry and Main have far fewer opportunities for functionality to "break".

## How should this be tested?
- Display in browser and monitor dev tools for error and warning messages.  Working on Cypress testing next.

## What are the next steps?
- Implement 500 and 404 error handling functionality, build out Cypress testing, and refactor CSS for responsiveness.

### CODE REVIEW

File: src/components/App/App.js [hunk 1]
```diff
@@ -1,101 +1,291 @@
...
+    this.getDataByCategory()
+      .then(() => {
+        this.setState({ dataLoaded: true })
       })
   }
 
-  getDataByCategory = (category) => {
-    apiCalls.fetchDataByCategory(category)
+  getDataByCategory = () => {
+    apiCalls.fetchDataByCategory(this.state.category)
```
Comment (kristenmb) [inline src/components/App/App.js]: A truly tiny note and definitely a preference thing, but I like cleaning these up by exporting each api call function separately (rather than in one larger object) and then importing the destructured functions you need. Feels a bit more readable to me.

Example:
`import { fetchDataByCategory, otherFetchCalls } from 'filepath-to-api-calls'`

File: src/components/App/App.js [hunk 2]
```diff
@@ -1,101 +1,291 @@
...
+      this.state.categoryData[key].forEach(elem => {
+        if (!elem['common_locations']) {
+          this.setState(prevState => ({
+            ...prevState,
+            backupItems: [...prevState.backupItems, elem],
+          }))
+        } else if (elem['common_locations'].includes(this.state.currentLocation)) {
+          this.setState(prevState => ({
+            ...prevState,
+            localItems: [...prevState.localItems, elem],
```
Comment (kristenmb) [inline src/components/App/App.js]: This is such a great use of `Object.keys`, array prototypes, and bracket notation, as well as react principles! Really proving that you've absorbed/retained mod 2 and 3 material - great job!

File: src/components/App/App.js [hunk 3]
```diff
@@ -1,101 +1,291 @@
...
+      this.setState(prevState => ({...prevState,
+        itemCards: 
+          [...prevState.itemCards, 
+            <Card item={item} id={item.id} key={parseInt(item.id)} /> 
+          ],
+      }))
+    };
+  }
+
+  resetItemData = () => {
```
Comment (kristenmb) [inline src/components/App/App.js]: Great clean way to reset everything

File: src/components/App/App.js [hunk 4]
```diff
@@ -1,101 +1,291 @@
...
+                  resetData={this.resetItemData}
                 />
-            }>
-            </Route>
-          </Switch>
-        </Router>
+              </Route>
+            </Switch>
+          </Router>
+        }
```
Comment (kristenmb) [inline src/components/App/App.js]: Another cool thing you can do with Router is create basically a wild card route that will lead to a 404 or error component - its a nice piece of user friendly error handling that can just say "This page doesn't exist" or something with a link back to home. It basically would only be triggered by an incorrect/unrecognized url but its a nice touch! You could potentially reuse your existing Error component.

Example:
`<Route path='/*' render={() => <Error />} />`

File: src/components/Card/Card.js [hunk 5]
```diff
@@ -1,85 +1,119 @@
...
+        } else {
+          return (
+            <div className='item-variables'>
+              <h3>Common Locations</h3>
+              <p className='item-common-locations'>{checkPropValidity('common_locations')}</p>
+              <h3>Drops</h3>
+              <p className='item-drops'>{checkPropValidity('drops')}</p>
+            </div>
+          );
+        }
```
Comment (kristenmb) [inline src/components/Card/Card.js]: Super cool use of a switch here - I like this application of it. I always struggled finding a good use case

File: src/components/Card/Card.js [hunk 6]
```diff
@@ -1,85 +1,119 @@
...
+import PropTypes from 'prop-types';
 
-class Card extends Component {
-  constructor({ item }) {
-    super()
-    this.state={
-      item: item,
-    }
-  }
+function Card({ item }) {
```
Comment (kristenmb) [inline src/components/Card/Card.js]: Nice clean up here from a class component to a functional comp! 

Not a criticism, just curious why you're choosing to use ES5 syntax for your functional components? I don't think it really matters either way, but I always aim to be as consistent as possible with my syntax

File: src/components/EntryPage/Entry.js [hunk 7]
```diff
@@ -30,10 +31,12 @@ function Entry({ locations, assignLocation }) {
   return (
     <main className='entry-page shine' onMouseOver={utils.addShimmerEffect}>
       <header className='banner'>
-        <h1 className='app-title' id='app-title'>HOOKSHOT</h1>
-        <h4 className='app-subtitle'>
+        <Link to={'/'} onClick={resetData}>
```
Comment (kristenmb) [inline src/components/EntryPage/Entry.js]: I really like this feature! Reset/Home button is great.

File: src/components/MainPage/Main.js [hunk 8]
```diff
@@ -1,59 +1,68 @@
 import React, { useState, useEffect } from 'react';
 import { Link } from 'react-router-dom';
-import categories from '../../datasets/categories';
+import PropTypes from 'prop-types';
+import categories from '../../utilities/categories';
 import utils from '../../utilities/utils';
 
-function Main({ location }) {
+function Main (
```
Comment (kristenmb) [inline src/components/MainPage/Main.js]: Really appreciate the way you've formatted things to be as readable as possible.

File: src/components/MainPage/Main.js [hunk 9]
```diff
@@ -1,59 +1,68 @@
...
+    assignCategory, 
+    resetData,
+    activateRandomState,
+  }) {
 
   const [ currentLocation, setCurrentLocation ] = useState('');
   const [ buttons, setButtons ]  = useState([]);
 
   useEffect(() => {
     const formatted = location.replaceAll('+', ' ');
```
Comment (kristenmb) [inline src/components/MainPage/Main.js]: Such a clean way to reformat - great usage here

**Review by kristenmb — COMMENTED** [review]
This is looking great, Pete! Its super clean and readable, I can see where and why you made some big choices about data flow and reusability of components. You're demonstrating a really firm grasp on React concepts as well as mod 1 and 2 fundamentals. Great usage of SCSS as well  🎉 I'm excited to see the final product! 

Are you planning on deploying? Because you should! 

Let me know if you have any questions and I'll be happy to provide more context - overall a really solid project and you're in a great spot for the deadline!

File: src/components/App/App.js (hunk 1 above)
Comment (pcmueller) [reply src/components/App/App.js]: Good to know - I've wondered about best practices for that, and keep going back and forth.  I'll split em up  👍

File: src/components/Card/Card.js (hunk 6 above)
Comment (pcmueller) [reply src/components/Card/Card.js]: Ah good catch - not even a conscious choice, just force of habit.  Thanks for pointing that out, I'll convert all functions to ES6 syntax.

File: src/components/App/App.js (hunk 4 above)
Comment (pcmueller) [reply src/components/App/App.js]: Oh perfect!  404 error handling was on my list, this is exactly what I was looking for.
